#!/bin/bash
OLD_CLASPATH=$CLASSPATH
. $IGRID_HOME/configs/minClasspath

CMD=""
for ARG in "$@"; do
    CMD="$CMD \"$ARG\""
done
bash -c "export IGRID_HOME=\"$IGRID_HOME_SBIN\"; java -classpath \"$CLASSPATH_SBIN\" sorcer.client.ClientUtils -sbin scu $CMD"
export CLASSPATH=$OLD_CLASSPATH
