// GENERATED CODE - MODIFICATIONS WILL BE LOST
// Version class generated by Version ant task - (C) Copyright 2002 dr. Cristiano Sadun; licensed under GPL
package org.sadun.text.ffp.version;

/**
 * This class is automatically generated by the org.sadun.util.ant.Version ANT task
 * to encapsulate version information. 
 */
public final class Version extends org.sadun.util.VersionImpl {
   public Version() {
     super(1,2,0,null,1L,1256655282240L);
   }

   public Version(int major, int minor, int micro) {
     super(major, minor, micro,null,1L,1256655282240L);
   }

   public static void main(String args[]) { 
    System.out.println(new Version().getFullDescription());
   }
}
